// IBCS App Schema for InstantDB
import { i } from '@instantdb/react';

const _schema = i.graph(
  {
    admins: i.entity({
      username: i.string().unique().indexed(),
      usernameLower: i.string().optional().unique().indexed(),
      password: i.string(),
      firstName: i.string(),
      lastName: i.string(),
      displayName: i.string(),
      createdAt: i.string(),
    }),
    teachers: i.entity({
      username: i.string().unique().indexed(),
      usernameLower: i.string().optional().unique().indexed(),
      password: i.string(),
      firstName: i.string(),
      lastName: i.string(),
      displayName: i.string(),
      createdAt: i.string(),
      archivedAt: i.string().optional(),
    }),
    classes: i.entity({
      className: i.string(),
      description: i.string().optional(),
      teacherId: i.string().indexed(),
      teacherUsername: i.string().indexed(),
      yearGroup: i.string().optional(),
      createdAt: i.string(),
      archivedAt: i.string().optional(),
    }),
    students: i.entity({
      username: i.string().optional().indexed(),
      usernameLower: i.string().optional().unique().indexed(),
      password: i.string(),
      firstName: i.string(),
      lastName: i.string(),
      displayName: i.string(),
      yearGroup: i.string(),
      curriculumTrack: i.string(),
      classId: i.string().indexed(),
      teacherId: i.string().indexed(),
      teacherUsername: i.string().indexed(),
      activeStage: i.string(),
      status: i.string(),
      archivedAt: i.string().optional(),
      createdAt: i.string(),
    }),
    classUnlocks: i.entity({
      classId: i.string().indexed(),
      teacherId: i.string().indexed(),
      teacherUsername: i.string().indexed(),
      stageKey: i.string(),
      unlockedBy: i.string(),
      unlockedAt: i.string(),
    }),
    studentUnlocks: i.entity({
      studentId: i.string().indexed(),
      classId: i.string().indexed(),
      teacherId: i.string().indexed(),
      teacherUsername: i.string().indexed(),
      stageKey: i.string(),
      unlockedBy: i.string(),
      unlockedAt: i.string(),
      scope: i.string(),
      targetId: i.string().optional(),
    }),
    lessons: i.entity({
      slug: i.string().unique().indexed(),
      title: i.string(),
      stageKey: i.string(),
      order: i.number(),
      createdAt: i.string(),
      isActive: i.boolean().optional(),
    }),
    studentProgress: i.entity({
      studentId: i.string().indexed(),
      lessonSlug: i.string().indexed(),
      classId: i.string().indexed(),
      teacherId: i.string().indexed(),
      teacherUsername: i.string().indexed(),
      status: i.string(),
      formativeAttempts: i.number().optional(),
      summativeScore: i.number().optional(),
      updatedAt: i.string(),
    }),
    classPacing: i.entity({
      classId: i.string().indexed(),
      track: i.string().optional(),
      unitId: i.string(),
      lessonId: i.string(),
      deckId: i.string().optional(),
      slideId: i.string().optional(),
      sessionCode: i.string().optional(),
      sessionStatus: i.string().optional(),
      sessionStartedAt: i.string().optional(),
      history: i.array(i.string()).optional(),
      accessibleSlides: i.array(i.json()).optional(),
      metadata: i.json().optional(),
      updatedAt: i.string(),
      updatedBy: i.string().optional(),
    }),
    studentGamification: i.entity({
      studentId: i.string().unique().indexed(),
      xp: i.number(),
      level: i.number(),
      streak: i.number(),
      totalCorrect: i.number(),
      totalAttempts: i.number(),
      lastUpdated: i.string(),
    }),
    liveAssessmentStatus: i.entity({
      classId: i.string().indexed(),
      unitId: i.string().indexed(),
      segmentId: i.string().indexed(),
      studentId: i.string().indexed(),
      attempts: i.number(),
      status: i.string(), // e.g., 'not-started', 'in-progress', 'completed'
      score: i.number().optional(),
      lastUpdated: i.string(),
    }),
    liveSessions: i.entity({
      classId: i.string().indexed(),
      lessonId: i.string().indexed(),
      lessonKey: i.string().optional(),
      deckId: i.string().indexed(),
      status: i.string(),
      pointer: i.json().optional(),
      slideHistory: i.array(i.string()).optional(),
      activeAssessments: i.array(i.json()).optional(),
      startedAt: i.number().optional(),
      attendance: i.json().optional(),
      sessionCode: i.string().optional().indexed(),
      updatedAt: i.string().optional(),
    }),
    studentStates: i.entity({
      sessionId: i.string().indexed(),
      studentId: i.string().indexed(),
      classId: i.string().indexed(),
      currentPosition: i.number().optional(),
      currentSlideId: i.string().optional(),
      viewedSlides: i.array(i.string()).optional(),
      timePerSlide: i.json().optional(),
      isActive: i.boolean().optional(),
      isBehind: i.boolean().optional(),
      lastHeartbeat: i.number().optional(),
    }),
    assessmentResponses: i.entity({
      sessionId: i.string().indexed(),
      studentId: i.string().indexed(),
      assessmentId: i.string().indexed(),
      attempts: i.array(i.json()),
      isComplete: i.boolean(),
      score: i.number().optional(),
      lastUpdated: i.number().optional(),
    }),
    analytics: i.entity({
      type: i.string().indexed(),
      sessionId: i.string().indexed(),
      classId: i.string().indexed(),
      studentId: i.string().optional(),
      slideId: i.string().optional(),
      timestamp: i.number(),
      payload: i.json().optional(),
    }),
    slideMetrics: i.entity({
      slideId: i.string().indexed(),
      averageViewTime: i.number().optional(),
      totalViews: i.number().optional(),
    }),
  },
  {}
);

type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
